package com.ruuvi.station.network.domain

object NetworkSettingNames {
    const val BACKGROUND_SCAN_MODE = "BACKGROUND_SCAN_MODE"
    const val BACKGROUND_SCAN_INTERVAL = "BACKGROUND_SCAN_INTERVAL"
    const val UNIT_TEMPERATURE = "UNIT_TEMPERATURE"
    const val UNIT_HUMIDITY = "UNIT_HUMIDITY"
    const val UNIT_PRESSURE = "UNIT_PRESSURE"
    const val ACCURACY_TEMPERATURE = "ACCURACY_TEMPERATURE"
    const val ACCURACY_HUMIDITY = "ACCURACY_HUMIDITY"
    const val ACCURACY_HUMIDITY_RELATIVE = "ACCURACY_HUMIDITY_RELATIVE"
    const val ACCURACY_HUMIDITY_ABSOLUTE = "ACCURACY_HUMIDITY_ABSOLUTE"
    const val ACCURACY_HUMIDITY_DEW_POINT = "ACCURACY_HUMIDITY_DEW_POINT"
    const val ACCURACY_PRESSURE = "ACCURACY_PRESSURE"
    const val ACCURACY_PM = "ACCURACY_PM"
    const val ACCURACY_ACCELERATION = "ACCURACY_ACCELERATION"
    const val ACCURACY_VOLTAGE = "ACCURACY_VOLTAGE"
    const val DASHBOARD_TYPE = "DASHBOARD_TYPE"
    const val DASHBOARD_TAP_ACTION = "DASHBOARD_TAP_ACTION"
    const val PROFILE_LANGUAGE_CODE = "PROFILE_LANGUAGE_CODE"
    const val CLOUD_MODE_ENABLED = "CLOUD_MODE_ENABLED"
    const val CHART_SHOW_ALL_POINTS = "CHART_SHOW_ALL_POINTS"
    const val CHART_DRAW_DOTS = "CHART_DRAW_DOTS"
    const val SENSOR_ORDER = "SENSOR_ORDER"
    const val DISABLE_EMAIL_NOTIFICATIONS = "DISABLE_EMAIL_NOTIFICATIONS"
    const val DISABLE_PUSH_NOTIFICATIONS = "DISABLE_PUSH_NOTIFICATIONS"
    const val DISABLE_TELEGRAM_NOTIFICATIONS = "DISABLE_TELEGRAM_NOTIFICATIONS"
    const val TIPS_ALLOWED = "TIPS_ALLOWED"
    const val MARKETING_PERMISSION = "MARKTING_PERMISSION"

    val TRACKED_SETTINGS = listOf(
        BACKGROUND_SCAN_MODE,
        BACKGROUND_SCAN_INTERVAL,
        UNIT_TEMPERATURE,
        UNIT_HUMIDITY,
        UNIT_PRESSURE,
        ACCURACY_TEMPERATURE,
        ACCURACY_HUMIDITY,
        ACCURACY_HUMIDITY_RELATIVE,
        ACCURACY_HUMIDITY_ABSOLUTE,
        ACCURACY_HUMIDITY_DEW_POINT,
        ACCURACY_PRESSURE,
        ACCURACY_PM,
        ACCURACY_ACCELERATION,
        ACCURACY_VOLTAGE,
        DASHBOARD_TYPE,
        DASHBOARD_TAP_ACTION,
        PROFILE_LANGUAGE_CODE,
        CLOUD_MODE_ENABLED,
        CHART_SHOW_ALL_POINTS,
        CHART_DRAW_DOTS,
        SENSOR_ORDER,
        DISABLE_EMAIL_NOTIFICATIONS,
        DISABLE_PUSH_NOTIFICATIONS,
        DISABLE_TELEGRAM_NOTIFICATIONS,
        TIPS_ALLOWED,
        MARKETING_PERMISSION
    )
}
