name: Android Test Build

on:
  pull_request:
    branches: [ dev, master, 'milestone/**' ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better SonarCloud analysis
      
    - name: set up JDK 17
      uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
      with:
        distribution: 'corretto'
        java-version: 17

    - name: Cache Gradle packages
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run localization script
      run: ./scripts/ci/update_l10n.sh

    - name: Run unit tests
      run: ./gradlew :app:testWithoutFileLogsDebugUnitTest --continue

    - name: Generate JaCoCo coverage report
      run: ./gradlew :app:jacocoTestReport

    - name: Verify JaCoCo coverage report
      run: test -s app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

    - name: SonarCloud Scan
      run: ./gradlew sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build debug variants
      run: ./gradlew assembleWithFileLogsDebug assembleWithoutFileLogsDebug

    - name: Save downloadable APKs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ruuvi-station-android-pr-debug-apks
        path: app/build/outputs/apk/*/debug/*.apk
        if-no-files-found: error
